name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  win-build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet publish 'Femc Config Adjuster' -c Release -o build

    - name: Zip Build
      run: Compress-Archive -Path build/* -DestinationPath FemcConfigAdjuster.zip

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-build
        path: FemcConfigAdjuster.zip
        retention-days: 0

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: FemcConfigAdjuster.zip
        fail_on_unmatched_files: true