name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  win-build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Update APP_VERSION to Match Tag
      run: |
        $filePath = "./Femc Config Adjuster/App.xaml.cs"
        $tag = "${{ github.ref_name }}"
        $regex = '^v?(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$'
        if ($tag -match $regex) {
          $newVersion = $tag.TrimStart('v')
          $content = Get-Content $filePath -Raw
          $content = $content -replace 'public const string APP_VERSION = ".*";', "public const string APP_VERSION = `"$newVersion`";"
          Set-Content -Path $filePath -Value $content
          Write-Host "APP_VERSION updated to $newVersion"
        } else {
          Write-Error "Tag format does not match expected MAJOR.MINOR.PATCH format: $tag"
        }
  
    - name: Commit Version Update
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b temp-branch  # Create a temporary branch
        git add "Femc Config Adjuster/App.xaml.cs"  # Add updated file
        git commit -m "Update APP_VERSION to match tag ${{ github.ref_name }}"  # Commit changes
        git push origin temp-branch:master  # Push to master branch

    - name: Build
      run: dotnet publish 'Femc Config Adjuster' -c Release -o build

    - name: Zip Build
      run: Compress-Archive -Path build/* -DestinationPath FemcConfigAdjuster.zip

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-build
        path: FemcConfigAdjuster.zip
        retention-days: 0

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: FemcConfigAdjuster.zip
        fail_on_unmatched_files: true
